# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170122_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='article',
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
